/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import MainContent from "./MainContent";
import Footer from "./Footer";
import styles from "./Apps.module.css";


const Apps = () => {
  return (
    <div className={styles.app}>
      <Header />
      <MainContent />
      <Footer />
    </div>
  );
};

export default Apps;
