/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CompanyInfo.module.css";

const CompanyInfo = () => {
  return (
    <section className={styles.companyInfo}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/e086bbabdfbaea45fc6e74f3f6be9dfc1d8d2355b2be438892f4435e95c0e167?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
        alt="Company logo"
        className={styles.logo}
      />
      <h1>Contact US</h1>
      <p className={styles.description}>
        Welcome to Glorious Fbric Pvt Ltd.
      </p>
      
    </section>
  );
};

export default CompanyInfo;
