/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactInfo.module.css";

const ContactDetail = ({ label, children }) => (
  <>
    <h2 className={styles.contactLabel}>{label}</h2>
    <p className={styles.contactDetail}>{children}</p>
  </>
);

function ContactInfo() {
  return (
    <section className={styles.contactInfo}>
      <div className={styles.contactDetail}> 
      <div className={styles.contactInfo}> 
      <ContactDetail label="Address :">
        GLORIOUS FABRIC PVT LTD, <br />
        182/C, <br />
        KANDEWATTE ROAD MALWANA
      </ContactDetail>
      
      
     
      <ContactDetail label="E-mail :">info@gloriousfabric.lkExplore</ContactDetail>
      <h2 className={styles.phoneLabel}>Tele Phone Num :</h2>
      <p>
       0776769398 <br />
       0773315775
      </p>
      </div></div>
    </section>
  );
}

export default ContactInfo;
