/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./ContactForm.module.css";

const ContactForm = () => {
  return (
    <section className={styles.contactSection}>
      <h2 className={styles.title}>Contact US</h2>
      <form className={styles.form}>
        <div className={styles.formGroup}>
          <label htmlFor="name" className={styles.label}>
            Name
          </label>
          <input type="text" id="name" className={styles.input} />
        </div>
        <div className={styles.formGroup}>
          <label htmlFor="email" className={styles.label}>
            Email
          </label>
          <input type="email" id="email" className={styles.input} />
        </div>
        <div className={styles.formGroup}>
          <label htmlFor="message" className={styles.label}>
            Message
          </label>
          <textarea id="message" className={styles.textarea}></textarea>
        </div>
        <button type="submit" className={styles.submitButton}>
          Send Message
        </button>
      </form>
    </section>
  );
};

export default ContactForm;
