/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./Header.module.css";

const Header = () => {
  const navItems = ["HOME", "PRODUCT", "ABOUT US", "CONTACT US"];

  return (
    <header className={styles.header}>
      <nav className={styles.nav}>
        {navItems.map((item, index) => (
          <a key={index} href="#" className={styles.navItem}>
            {item}
          </a>
        ))}
        <a href="#" className={styles.login}>
          LOGIN
        </a>
      </nav>
    </header>
  );
};

export default Header;
