/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./LocationSection.module.css";

const LocationSection = () => {
  return (
    <section className={styles.locationSection}>
      
      <div className={styles.locationInfo}>
        <h2>Location :</h2>
        <iframe width="300" height="360" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=405&amp;height=280&amp;hl=en&amp;q=glorious%20house,%20kanda%20waththa%20road%20malwana+(GLORIOUS%20HOUSE)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.gps.ie/">gps vehicle tracker</a></iframe>
      </div>
    </section>
  );
};

export default LocationSection;
