/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./LocationSection.module.css";

const LocationSection = () => {
  return (
    <section className={styles.locationSection}>
      <img
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/7fd91e2a016e78b4576b4c2d31ce0e0013acb947e460022a64c3d363694933f8?placeholderIfAbsent=true&apiKey=2ced3db22aac4ec9b3a268650a41a373"
        alt="Company building"
        className={styles.companyImage}
      />
      <div className={styles.locationInfo}>
        <h2>Location :</h2>
        <iframe width="405" height="280" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=405&amp;height=280&amp;hl=en&amp;q=Colombo%2000700+(Alexandra%20Pl)&amp;t=&amp;z=14&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"><a href="https://www.gps.ie/">gps vehicle tracker</a></iframe>
      </div>
    </section>
  );
};

export default LocationSection;
