/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./MainContent.module.css";
import LocationSection from "./LocationSection";
import CompanyInfo from "./CompanyInfo";
import ContactForm from "./ContactForm";
import ContactInfo from "./ContactInfo";

const MainContent = () => {
  return (
    <main className={styles.mainContent}>
      <div className={styles.contentWrapper}>
        <div className={styles.leftColumn}>
          <LocationSection />
        </div>
        <div className={styles.rightColumn}>
          <CompanyInfo />
          <div className={styles.contentWrapper}>
          <div className={styles.leftColumn}>
          <ContactInfo />
          </div>
        <div className={styles.rightColumn}>
          <ContactForm />
        </div>
        </div>
        </div>
      </div>
    </main>
  );
};

export default MainContent;
